lyra_admin:
    theme: ui-lightness
    models:
        listing:
            class: 'Acme\ClassifiedsBundle\Entity\Listing'
            controller: 'AcmeClassifiedsBundle:Admin'
            # title displayed in top menu
            title: Listings
            services:
                # service id of user defined model manager
                # see Acme/ClassifiedsBundle/Resources/config/services.yml
                model_manager: acme_classifieds.listing_manager
            actions:
                publish:
                    # for batch actions it's the text displayed in drop down list
                    text: Publish
                unpublish:
                    text: Unpublish
                new:
                    # for list/object actions it's the button text
                    text: 'New listing'
                    # button icon
                    icon: circle-plus
                expired:
                    route_pattern: expired
                    text: 'Delete expired'
                    icon: trash
                    dialog:
                        title: 'Confirm delete expired'
                        message: 'Do you really want to delete all expired listings?'
            show:
                title: Listing
                fields:
                    category: ~
                    ad_title: ~
                    posted_at: ~
                    published: ~
            list:
                title: Listings
                default_sort:
                    column: posted_at
                    order: desc
                columns:
                    category:
                        field: category.name
                        label: Category
                    ad_title: ~
                    published:
                        sortable: false
                    posted_at:
                        label: Date
                        format: 'j/M/Y'
                batch_actions: [publish,unpublish,delete]
                list_actions: [new,expired]
            filter:
                # search dialog title
                title: 'Search listings' 
                fields:
                    category: ~
                    ad_title: ~
                    posted_at:
                        widget: daterange
                        options:
                            child_widget: datetime_picker
                    published: ~
            fields:
                expires_at:
                    widget: datetime_picker
            form:
                groups:
                    listing:
                        # panel title
                        caption: Listing
                        fields: [category,ad_title,ad_text]
                        # column break after this panel
                        break_after: true
                    status:
                        caption: Status
                        fields: [published,expires_at]
        category:
            class: 'Acme\ClassifiedsBundle\Entity\Category'
            title: Categories
            list:
                title: 'Listing categories'
                columns:
                    name: ~
                    description: ~

