parameters:
    mgi_classifieds.listing_manager.class: MGI\ClassifiedsBundle\Model\ListingManager

services:
    mgi_classifieds.listing_manager:
        class: %mgi_classifieds.listing_manager.class%
