parameters:
    acme_classifieds.listing_manager.class: Acme\ClassifiedsBundle\Model\ListingManager

services:
    acme_classifieds.listing_manager:
        class: %acme_classifieds.listing_manager.class%
